server:
  port: 9191
spring:
  h2:
    console:
      enabled: true
  application:
    name: PAYMENT-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: D:/Qualigytech-Springboot/elk_logs_folder/microservices_elk_logs.log



#resilience4j:
#  circuitbreaker:
#    instances:
#      PAYMENT-SERVICE:
#        register-health-indicator: true
#        event-consumer-buffer-size: 10
#        failure-rate-threshold: 40
#        minimum-number-of-calls: 3
#        automatic-transition-from-open-to-half-open-enabled: true
#        wait-duration-in-open-state: 10s
#        permitted-number-of-calls-in-half-open-state: 3
#        sliding-window-size: 10
#        sliding-window-type: COUNT_BASED
  # real time we need add max 2s duration and max attempt 2-3 times
#  retry:
#    instances:
#      userService:
#        max-attempts: 5
#        wait-duration: 10s